### ISSUE TITLE
Implement dmnlint-pack-config 

### ISSUE THREAD

**Issue by codygulley** [bpmn-io/dmn-js-dmnlint#2]
__Is your feature request related to a problem? Please describe__

Feature Request to add ability to pack ```.dmnlintrc```

__Describe the solution you'd like__

The ability to pack/bundle `.dmnlintrc` into a generated dmnlint rules file for use in a browser.
(Just like with bpmnlint which provides the package [bpmnlint-pack-config ](https://github.com/nikku/bpmnlint-pack-config) for packing) 

__Describe alternatives you've considered__

There are no other packages available for dmnlint bundle and the package referenced in README is still TODO.

__Additional context__

Please provide a package for packing `.dmnlintrc`. 

The readme suggests that you need to bundle rules for use in a browser however the package referenced does not exist dmnlint-pack-config is still TODO in the readme. 

> Alternatively, pack your local .dmnlintrc file using the [dmnlint-pack-config (TODO)](https://github.com/nikku/dmnlint-pack-config) utility:
```dmnlint-pack-config -c .dmnlintrc -o bundled-config.js```

**Comment by pinussilvestrus** [comment]
Thanks for reporting! As this is not on our immediate roadmap, I'm moving this to the backlog. We are open to contributions that improve the situation 👍

**Comment by codygulley** [comment]
@pinussilvestrus I will gladly implement as I have a mostly working code already based on [bpmnlint-pack-config](https://github.com/nikku/bpmnlint-pack-config) and [rollup-plugin-bpmnlint](https://github.com/nikku/rollup-plugin-bpmnlint). 

What is the standard practice/policy for getting these repositories created as I'd like for to inner-source these to bpmn-io rather than having them live under my user account.  Would you create the blank repositories (dmnlint-pack-config and rollup-plugin-dmnlint) and I open PRs or would I create the repositories under my account and transfer ownership to bpmn-io ? 

Looking forward to how I can contribute the work i've done!

**Comment by pinussilvestrus** [comment]
> @pinussilvestrus I will gladly implement as I have a mostly working code already based on [bpmnlint-pack-config](https://github.com/nikku/bpmnlint-pack-config) and [rollup-plugin-bpmnlint](https://github.com/nikku/rollup-plugin-bpmnlint).
> 
> What is the standard practice/policy for getting these repositories created as I'd like for to inner-source these to bpmn-io rather than having them live under my user account. Would you create the blank repositories (dmnlint-pack-config and rollup-plugin-dmnlint) and I open PRs or would I create the repositories under my account and transfer ownership to bpmn-io ?
> 
> Looking forward to how I can contribute the work i've done!

Thanks for your willingness to contribute! I just checked our existing packages and found that [`rollup-plugin-dmnlint`](https://github.com/bpmn-io/rollup-plugin-dmnlint) already exists. I just created a repository for [`dmnlint-pack-config`](https://github.com/bpmn-io/dmnlint-pack-config), so feel free to file a PR to that 👍

**Comment by codygulley** [comment]
[pinussilvestrus](https://github.com/pinussilvestrus) Thanks! I don't how how I missed the existing [rollup-plugin-dmnlint](https://github.com/bpmn-io/rollup-plugin-dmnlint) package !

Regarding the newly created [dmnlint-pack-config](https://github.com/bpmn-io/dmnlint-pack-config)  - I can't fork or do a PR because the repository is empty. Do you mind adding and pushing an empty README so that becomes enabled?

**Comment by pinussilvestrus** [comment]
Sorry for that, I just added some dummy content 👍

**Comment by codygulley** [comment]
That did the trick!  I've created [a PR ](https://github.com/bpmn-io/dmnlint-pack-config/pull/1) into that repo. 

@pinussilvestrus If you'd like you can close this issue now as it does not relate to this repository and can anything pertaining can be handle via that PR/repo. 
I appreciate your quick responses!

**Comment by pinussilvestrus** [comment]
Thanks a lot, we will have a look 👍
